# Generated by Django 4.2.6 on 2023-10-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('type1', 'Sunny'), ('type2', 'Cloudy'), ('type3', 'Windy'), ('type4', 'Rainy'), ('type5', 'Stormy')], default='type1', max_length=100),
        ),
    ]
