# Generated by Django 4.2.4 on 2023-10-06 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 6, 19, 36, 44, 266406, tzinfo=datetime.timezone.utc)),
        ),
    ]
